kind: Deployment
apiVersion: apps/v1
metadata:
  name: entso-e
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: image-registry.openshift-image-registry.svc:5000/demo/entso-e:latest
